### PR TITLE
Add new the API parameter - --api.

### LINKED ISSUE #20: --api
Let's make it possible to specify a list of APIs to use, in any particular order, for example:

```
--api=blockchain.info,chain.so,block.io
```

They should be used in this particular order. If the first one fails, the second one is attempted, and so on.

### PR DESCRIPTION
**Pull request by aivinog1**
I've added the new API parameter without implementation but with some todos.

This fixes #20.

### CODE REVIEW

**Comment by aivinog1** [comment]
@yegor256 Can you review this, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@aivinog1 looks good to me, let's try to merge

**Comment by aivinog1** [comment]
@yegor256 Seems like Rultor fails here: https://github.com/yegor256/sibit/blob/51e90b73c2a04444ef9713336c3de2a05426db81/.rultor.yml#L28 But it's not clear for me why. I'll create a new issue for that.

**Comment by aivinog1** [comment]
> @yegor256 Seems like Rultor fails here:
> 
> https://github.com/yegor256/sibit/blob/51e90b73c2a04444ef9713336c3de2a05426db81/.rultor.yml#L28
> But it's not clear for me why. I'll create a new issue for that.

I've create this: https://github.com/yegor256/sibit/issues/32

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@aivinog1 there are some issues, run `bundle exec rake` before submitting a pull request

**Comment by aivinog1** [comment]
@yegor256 sure. That because of the rubocop start looking in the bin dir. I'll fix that.

**Comment by aivinog1** [comment]
@yegor256 I've updated my branch and resolved all rubocop errors. Can you review this, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
